"""
Django settings for wallethold project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/

"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG == True:
    SECRET_KEY = '+mt@@i7jf#lk7g_-*=e9vdh!^u4a)6q9firl39(b--iqn$8hf$'

    ALLOWED_HOSTS = ['*']
    CSP_DEFAULT_SRC = ("'none'",)
    CSP_STYLE_SRC = ("'self'", "http://localhost", "fonts.googleapis.com",)
    CSP_SCRIPT_SRC = ("'self'", "http://localhost",)
    CSP_IMG_SRC = ("'self'", "http://localhost",)
    CSP_FONT_SRC = ("'self'", "http://localhost")
    CSP_CONNECT_SRC = ("'self'", "http://localhost",)
    CSP_OBJECT_SRC = ("'none'",)
    CSP_BASE_URI = ("'none'",)
    CSP_FRAME_SRC = ("'self'",)

    CSP_FRAME_ANCESTORS = ("'none'",)
    CSP_FORM_ACTION = ("'self'", "http://localhost:8000",)
    CSP_INCLUDE_NONCE_IN = ('script-src',)

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


else:
    with open('/etc/secret_key.txt') as f:
        SECRET_KEY = f.read().strip()

    ALLOWED_HOSTS = [' <<< TU DOMINIO >>>']
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'Strict'
    CSRF_COOKIE_AGE = None
    CSRF_COOKIE_DOMAIN = None
    CSRF_USE_SESSIONS = False
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_PATH = '/;HttpOnly'
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Strict'
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True
    SESSION_COOKIE_AGE = 60 * 120

    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 15768000  # 3600  # 1 day
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_FRAME_DENY = True

    X_FRAME_OPTIONS = 'DENY'

    CSP_DEFAULT_SRC = ("'none'",)
    CSP_STYLE_SRC = (
        "'self'",)
    CSP_SCRIPT_SRC = ("'self'",)
    CSP_IMG_SRC = ("'self'",)
    CSP_FONT_SRC = ("'self'",)
    CSP_CONNECT_SRC = ("'self'",)
    CSP_OBJECT_SRC = ("'none'",)
    CSP_BASE_URI = ("'none'",)
    CSP_FRAME_SRC = ("'self'",)

    CSP_FRAME_ANCESTORS = ("'none'",)
    CSP_FORM_ACTION = ("'self'",)
    CSP_INCLUDE_NONCE_IN = ('script-src',)

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

PASSWORD_RESET_TIMEOUT_DAYS = 2

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'db',
    'crispy_forms',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'wallethold.urls'

REFERRER_POLICY = 'same-origin'

FEATURE_POLICY = {
    'geolocation': 'none',
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wallethold.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LOGIN_URL = '/inicia-sesion/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/inicia-sesion/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


if DEBUG == True:
    STATIC_URL = '/static/'
    STATIC_ROOT = ''
    STATICFILES_DIRS = (
        'static',
    )
else:
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

    os.environ['HTTPS'] = "on"
    os.environ['wsgi.url_scheme'] = 'https'

try:
    from .settings_private import *  # noqa
except ImportError:
    pass